# Generated by Django 4.2.4 on 2023-08-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='IMS.inventory'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='IMS.inventory'),
        ),
    ]
